chang plot model to fully support plotting submodel
ccgccc/ccg_test_repo pull request #1
Opened 2019-04-13 14:23 UTC by ccgcccccc

there are some explanations

2019-04-13 16:29 UTC, ccgcccccc commented on keras/utils/vis_utils.py
> +        dot = pydot.Cluster(style='dashed', graph_name=model.name)
this is to prevent different submodel confusing

2019-04-13 16:34 UTC, ccgccc requested changes

2019-04-13 16:34 UTC, ccgccc commented on keras/utils/vis_utils.py
> +                 #subgraph=True):
```suggestion
                 #subgraph=True):
```
please remove unnessary comments

2019-04-13 16:34 UTC, ccgccc commented on keras/utils/vis_utils.py
> +
please remove

2019-04-13 16:34 UTC, ccgccc commented on test_file_created_when_merging.txt
> +test the influence of adding a unrelevant file when merging.
please remove this file

2019-04-13 17:05 UTC, ccgccc approved these changes

2019-04-14 07:11 UTC, ccgccc commented
Please make sure your codes meet PEP8 standard.

2019-04-14 13:32 UTC, ccgccc commented
please create another PR again.

2019-04-14 13:32 UTC, closed without merging